完成service的组长创建团队，组长添加、删除组员和组长修改团队信息的内容，及其对应的序列化，并对几个model和接口进行了补充
FZUSESPR21/PingLeMe-backend pull request #31
Opened 2021-05-03 16:16 UTC by shican45

Fixes  #22 #23 #24 #30

2021-05-03 16:31 UTC, shican45 commented
修改一些代码并修改关联issue

2021-05-04 02:25 UTC, ErrorPay requested changes

2021-05-04 02:25 UTC, ErrorPay commented on service/team_charge_service.go
> +	if errors.Is(err, gorm.ErrRecordNotFound) {
这里还要处理ErrRecordNotFound以外的其他错误

2021-05-04 02:25 UTC, ErrorPay commented on service/team_charge_service.go
> +type TeamChargeService struct {
名字推荐改成TeamManagementService

2021-05-04 02:37 UTC, shican45 commented
修改

2021-05-04 03:00 UTC, shican45 commented
修改

2021-05-04 03:04 UTC, shican45 commented
修改

2021-05-04 03:07 UTC, ErrorPay approved these changes

2021-05-04 03:07 UTC, merged